---
title: "Challenge 1 Instructions"
author: "Meredith Rolfe"
desription: "Reading in data and creating a post"
date: "08/15/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - challenge_1
---

```{r}
#| label: setup
#| warning: false
#| message: false

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


```{r}
#1st Dataset Railroad_2012_clean_county
library(readr)
railroad_2012_clean_county <- read_csv("posts/_data/railroad_2012_clean_county.csv")
view(railroad_2012_clean_county)
#2nd Dataset birds
birds <- read_csv("posts/_data/birds.csv")
View(birds)
```

```{r}
#| label: summary

#1st dataset Railroad_2012_clean_county
#It is about number of employees in each company
#there are 3 variables as can be seen using the colnames command- state, county, number of employees
colnames(railroad_2012_clean_county)
#number of employees- continuous variable
#Data was gathered from the following states
states<-select(railroad_2012_clean_county,state)
table(states)
prop.table(table(states))

#2nd dataset birds
#14 columns and 30977 observations
dim(birds) 
#What the different columns are
colnames(birds)
#From colnames, we get to know that the dataset gives us the values of the dietary energy intake for different countries across different years
#Data types of the columns, value could actually be converted into double type
str(birds)
birds <- transform(birds,value1 = as.numeric(Value))
#checking for missing values
sum(is.na(birds))
#removing missing values
birds<-na.omit(birds)
#checking the observations-around 11000 are removed
dim(birds)
area<-select(birds,Area)
#Data was collected from several countries across continents
table(area)
item<-select(birds,Item)
#6 types of birds as seen in item
table(item)
#only one domain of animals
domain<-select(birds,Domain)
table(domain)
#To see the changes in the Value across the years
plot(value1~Year,birds)
#it can be seen that the values have increased over time
#To see the changes in a specific country, for instance, the USA 
birds_USA<-birds%>% filter(`Area`=='United States of America')
plot(value1~Year,birds_USA)
```
